// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyeusjkivowioqxzwgpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZXVzamtpdm93aW9xeHp3Z3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTgyNDQsImV4cCI6MjA2OTI5NDI0NH0.M0_RjY2oEepFVBhg-Y4l_G9JrYCXm-UlXkEziDJAExc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});